---
name: Build on PR
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Generate version
        id: 666
        run: |
          VERSION="1.2.3"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: echo "Version ${{ needs.build.outputs.version }}"
