---
name: Build on PR
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        run: echo "1.2.3" > version.txt

      - name: Save to artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: version.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download version
        uses: actions/download-artifact@v4
        with:
          name: version-file

      - name: Read version
        run: cat version.txt
